#!/bin/bash
# Execute `platform.make` which will clone Drupal core among with our
# installation profile placing it into the appropriate folder (`profiles`).
if [ -d web ]; then
mv web web-old
fi

if [ "$DRUSH" == "" ]; then
DRUSH="drush"
fi

$DRUSH make --working-copy --no-gitinfofile platform.make web

if [ -d web-old ]; then
    # Sites all should be populated by our make file, so lets' remove that.
    rm -rf web-old/sites/all
    mv web/sites/all web-old/sites/.
    rm -rf web/sites
    mv web-old/sites web/sites
    rm -rf web-old
fi
